name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

#    - name: Cache Composer packages
#      id: composer-cache
#      uses: actions/cache@v3
#      with:
#        path: vendor
#        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
#        restore-keys: |
#          ${{ runner.os }}-php-

    - name: Clear Composer Cache
      run: rm var/cache -rf

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: PHP_CodeSniffer Check with Annotations
      uses: chekalsky/phpcs-action@v1.2.0

    - name: PHPUnit (php-actions)
      uses: php-actions/phpunit@v3
      with:
        version: 8.5.36,
        php_extensions: intl,
        configuration: phpunit.xml.dist

    - name: PHPStan (php-actions)
      uses: php-actions/phpstan@v3
      with:
          php_extensions: intl
